### ISSUE TITLE
Missing support for meta directive

### ISSUE THREAD

**Issue by pmkovar** [lruzicka/sphinx_asciidoc#5]
When building https://github.com/openstack/openstack-manuals/tree/master/doc/arch-design:

Output: https://docs.openstack.org/arch-design/

NotImplementedError: sphinx_asciidoc.writer.AsciiDocTranslator visiting unknown node type: meta

The offending syntax:

.. meta::
   :description: This guide targets OpenStack Architects
                 for architectural design
   :keywords: Architecture, OpenStack

**Comment by lruzicka** [comment]
The meta directive is now implemented, the Asciidoc output is:

:description: This guide targets OpenStack Architects for architectural design
:keywords: Architecture, OpenStack

If it is ok, please confirm. The change is now pushed. It will be available in the next release on PyPI. You can try for yourself if, you clone the repo, go to the repo root directory and run:
pip install -e .

**Comment by pmkovar** [comment]
Seems to work as expected, thanks!
