### ISSUE TITLE
Missing support for transition

### ISSUE THREAD

**Issue by pmkovar** [lruzicka/sphinx_asciidoc#6]
When building https://github.com/openstack/openstack-manuals/tree/master/doc/doc-contrib-guide:

NotImplementedError: sphinx_asciidoc.writer.AsciiDocTranslator visiting unknown node type: meta

Output: https://docs.openstack.org/doc-contrib-guide/rst-conv/decorations.html

The offending syntax (see the dashes):

**Input**

.. code-block:: none

   Paragraph 1

   ----

   Paragraph 2

**Output**

Paragraph 1

----

Paragraph 2

**Comment by lruzicka** [comment]
This issue does not cover the meta directive, but rather the transition directive. Anyway.
Support for this directive has been added. The directive produces a horizontal rule in html.
In asciidoc it produces the triple apostrophe to render a horizontal rule, see example. 

The support is added in the next commit. It will be available in the next release on PyPI.
Example:
<empty line>
`'''`
<empty line>
