### ISSUE TITLE
Missing support for manpage directive

### ISSUE THREAD

**Issue by pmkovar** [lruzicka/sphinx_asciidoc#7]
When building https://github.com/openstack/openstack-manuals/blob/master/doc/ha-guide:

Output: https://docs.openstack.org/ha-guide/controller-ha-identity

The offending syntax:

#. Edit the :file:`keystone.conf` file
   to change the values of the :manpage:`bind(2)` parameters:

**Comment by lruzicka** [comment]
I am not sure what this should do. I have checked the rendering in the above output, but the only thing I can see is `bind(2)` rendered as *bind(2)*. Is it correct?
If italics is the only issue here, I have added support for it. Otherwise, please let me know.
