### ISSUE TITLE
Missing support for tabularcolumns

### ISSUE THREAD

**Issue by pmkovar** [lruzicka/sphinx_asciidoc#8]
When building https://github.com/openstack/openstack-manuals/blob/master/doc/ha-guide/source/networking-ha-l3.rst:

Output: https://docs.openstack.org/ha-guide/networking-ha-l3

The offending syntax:

.. tabularcolumns:: |l|l|L|

**Comment by lruzicka** [comment]
Support for the above was added in the last commit. Please feel free to test, Petr.
